on:
  push:
    branches: master

name: Render index

jobs:
  render:
    name: Render index
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install remotes and rmarkdown
        run: |
          install.packages("remotes")
          remotes::install_cran("rmarkdown")
        shell: Rscript {0}
      - name: Render index
        run: |
          Rscript -e 'rmarkdown::render("index.Rmd")'
          Rscript -e 'file.exists("index.html")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add index.html
          git commit index.html -m 'Re-build index.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
